### ISSUE TITLE
Vorm ablauf von config keys warnen

### ISSUE THREAD

**Issue by staabm** [eaCe/transient#1]
**Feature description / Feature Beschreibung**
Ggf. Macht es sinn vor ablauf von keys den admin zu informieren sodass er zeit hat neue zu besorgen etc

**Comment by eaCe** [comment]
Ich hatte bisher nur an eine automatisierte Lösung gedacht. Also wenn nicht mehr vorhanden, neuen holen. 
Man könnte auch eine Mail senden. Werde ich nachrüsten.

**Comment by eaCe** [comment]
Ich werde das doch nicht nachrüsten. Man müsste das mit einem Cronjob prüfen. Der Zweck des Addons ist es eher, irgendwelche Tokens zu erneuern, wenn der Transient abgelaufen ist. Je nach Traffic würde das vielleicht nicht auffallen, wenn man keinen Cronjob nutzt. Davon abgesehen weiß ich nicht mal, ob das von irgendwem außer mir genutzt wird :)
