### ISSUE TITLE
rex_config-Tabelle nutzen statt eigener

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [eaCe/transient#3]
**Feature description / Feature Beschreibung**
Es wäre möglich, nur eine andere Methode bereitzustellen, die zwei config-Werte miteinander kombiniert - das hätte den Vorteil, dass das Addon interoperabel zu rex_config wäre.

**Comment by eaCe** [comment]
Ich hatte das eigentlich absichtlich getrennt. Der eigentliche Eintrag liegt auch in der Config, nur der Timer nicht. Ich kann das auch in die Config schreiben...

**Comment by AWqxKAWERbXo** [comment]
War einfach eine konzeptionelle Idee :)
